mandla_1/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('about/', views.about),

]

mandla_1/forms.py
from django import forms

class QueryForm(forms.Form):
    email = forms.CharField(label = 'Email address',max_length=100,widget= forms.TextInput
                           (attrs={'placeholder':'name@example.com'}))
    subject = forms.CharField(label = 'Subject', max_length=200,widget= forms.TextInput
                           (attrs={'placeholder':'Feed my dog'}))
    detail = forms.CharField(label="Describe in detail", max_length=2000)
# from django import forms

# class NameForm(forms.Form):
#     your_name = forms.CharField(label='Your name', max_length=100)

mandla_1/views.py
from django.urls import path
from . import views
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')


from django.views import View
from django.shortcuts import render, redirect
from .forms import QueryForm
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponse
# def index(request):
#     return render(request, "index.html")

def index(request):
    if request.method == 'POST':
        form = QueryForm(request.POST)
        # check whether it's valid:
        if form.is_valid():

            email = form.cleaned_data['email']
            subject =  form.cleaned_data['subject']
            details = form.cleaned_data['detail']

            rec = "ankurkumar93@protonmail.com"
            send_mail(subject,"email address is "+email+ " and concern is "+details,'parvaiziqra@gmail.com',['ankurkumar93@protonmail.com'], fail_silently=False)

            messages.success(request, "Thanks for your mail")

            return render(request, 'index.html', {'form': form})


    else:
        form = QueryForm()

    return render(request, 'index.html', {'form': form})

mandla_1/templates/about.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}

mandla_1/templates/base.html
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<title>Ekagra</title>
	<style src = '{% static "style.css" %}'></style>
	<style>
		#slideshow {
			position:relative;
			height:400px;
		}
		#slideshow DIV {
			position:absolute;
			top:0;
			left:0;
			z-index:8;
			opacity:0.0;
			height: 400px;
			background-color: #FFF;
		}
		#slideshow DIV.active {
			z-index:10;
			opacity:1.0;
		}
		#slideshow DIV.last-active {
			z-index:9;
		}
		#slideshow DIV IMG {
			height: 350px;
			display: block;
			border: 0;
			margin-bottom: 10px;
		}
		#id_email, #id_subject, #id_detail{
			width: 100%;
			margin-bottom: 20px;
			 
		}
		.label {
			margin-bottom: 10px;
		}
		#id_detail{
			height: 100px;
		}
		.my-form{
			/* background-color:blueviolet; */
			margin-left: 15%;
			margin-right: 15%;
			margin-bottom: 50px;
			margin-top: 50px;
		}
		.float-container {
			
			width: 80%;
			margin-left: auto;
			margin-right: auto;
			display: flex;
			justify-content: space-evenly;

		}
		

		.float-child {			
			height: fit-content;
			margin: 5px;
		} 
		.topnav {
			overflow: hidden;
			background-color: #333;
			position: relative;
		  }
		
		  .topnav #myLinks {
			display: none;
		  }
		
		  .topnav a {
			float: left;
			color: white;
			padding: 14px 16px;
			text-decoration: none;
			font-size: 17px;
		  }
		  .active {
			/* background-color: #4CAF50; */
			color: white;
		  }
		
		  .topnav a:hover {
			background-color: #ddd;
			color: black;
		  }
		
		
		
		  body {
			font-family: Arial, Helvetica, sans-serif;
		  }
		
		  .mobile-container {
			max-width: 480px;
			margin: auto;
			background-color: #555;
			height: 500px;
			color: white;
			border-radius: 10px;
		  }
		
		  .topnav {
			overflow: hidden;
			background-color: #333;
			position: relative;
		  }
		
		  .topnav #myLinks {
			display: none;
		  }
		
		  .topnav a {
			float: left;
			color: white;
			padding: 14px 16px;
			text-decoration: none;
			font-size: 17px;
		  }
		
		  .topnav a.icon {
			float: right;
		  }
		
		  .topnav a:hover {
			background-color: #ddd;
			color: black;
		  }
		
		  .active {
			/* background-color: #4CAF50; */
			color: white;
		  }
		.friends{
		  margin-top: 100px;
		}
		.prod-desc{
			text-align: center;
		}
		.buy-button{
			width: auto;
			
		}
		.btn{
			margin-left: auto;
			
			margin-right: auto;
			
		}
		
		.prod-head{
			text-align: center;
			margin-top: 50px;
			margin-bottom: 20px;
		}
		@media screen and (max-width:480px){
			.container-2{
				margin-top: -45px;
			}
			.card{
				margin-bottom: 20px;
			}
			.carousel-control-prev, .carousel-control-next{
				opacity: 0;
				visibility: hidden;
			}
			#myLinks{
				margin-left: 15px;
			}
			.row{
				margin-top: -100px;
			}
			.my-form{
				margin-top: 50px;
			}
			.row{
				margin-top: 50px;
				display: flex;
				flex-direction: column;
			}
			.col-4{
				width: 100%;
				margin-bottom: 50px;
				max-width: 100%;

			}
		}
		.responsive:hover{
			cursor: pointer;
		}
		.responsive{
			margin-top: 10px;
		}
		.d-block{
			margin-bottom: 10px;
		}
		
		
		.tooltip {
		  position: relative;
		  display: inline-block;
		}
		
		.tooltip .tooltiptext {
		  visibility: hidden;
		  width: 140px;
		  background-color: #555;
		  color: #fff;
		  text-align: center;
		  border-radius: 6px;
		  padding: 5px;
		  position: absolute;
		  z-index: 1;
		  bottom: 150%;
		  left: 50%;
		  margin-left: -75px;
		  opacity: 0;
		  transition: opacity 0.3s;
		}
		
		.tooltip .tooltiptext::after {
		  content: "";
		  position: absolute;
		  top: 100%;
		  left: 50%;
		  margin-left: -5px;
		  border-width: 5px;
		  border-style: solid;
		  border-color: #555 transparent transparent transparent;
		}
		
		.tooltip:hover .tooltiptext {
		  visibility: visible;
		  opacity: 1;
		}
		
</style>




<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Ekagra</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
  
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	  <ul class="navbar-nav mr-auto">
		<li class="nav-item active">
		  <a class="nav-link" href="#">Products <span class="sr-only">(current)</span></a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" href="#">About<span class="sr-only">(current)</span></a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#">Contact<span class="sr-only">(current)</span></a>
		  </li>		
	  </ul>
	</div>
  </nav>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

mandla_1/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
home
{% endblock %}

{% block content %}

        



<body>
<div class="container">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img class="d-block w-100" src="{% static '../static/images/ekagra img1.jpg' %}" alt="second slide" style="height:600px;width:400px">
      
    </div>
    <div class="carousel-item">
        <img class="d-block w-100" src="{% static '../static/images/ekagra img4.jpg' %}" alt="second slide" style="height:600px;width:400px">
      
    </div>
    <div class="carousel-item">
        <img class="d-block w-100" src="{% static '../static/images/ekagra img2.jpg' %}" alt="second slide" style="height:600px;width:400px">
      
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div> 


<!-- {% comment %} products {% endcomment %} -->
      <div id="getaquote"style="border-bottom: ridge; margin-left: auto; margin-right: auto;width: 70%; margin-bottom: 50px; margin-top: 60px; text-align: center;"><h2>Products</h2></div>

<div class=" float-container">
  <div class="row justify-content-center">
    <div class="col-4">
        <img class="d-block w-100" src="{% static '../static/images/ekagra img4.jpg' %}" alt="second slide" style="height:400px;width:400px">
        <p class="prod-desc">this is a mandla art and it is worth buying. it is 12X10 inches</p>
      <div class="btn"><button class="btn btn-primary"><i class="fas fa-shopping-cart mr-1"></i> Buy now</button></div>
    </div>
    <div class="col-4">
        <img class="d-block w-100" src="{% static '../static/images/ekagra img4.jpg' %}" alt="second slide" style="height:400px;width:400px">
        <p class="prod-desc">this is a mandla art and it is worth buying. it is 12X10 inches</p>
      <div class="btn"><button class="btn btn-primary"><i class="fas fa-shopping-cart mr-1"></i> Buy now</button></div>
      
    </div>
  </div>
</div>
<div class=" float-container container-2">
  <div class="row justify-content-center">
    <div class="col-4">
        <img class="d-block w-100" src="{% static '../static/images/ekagra img4.jpg' %}" alt="second slide" style="height:400px;width:400px">
        <p class="prod-desc">this is a mandla art and it is worth buying. it is 12X10 inches</p>
      <div class="btn"><button class="btn btn-primary"><i class="fas fa-shopping-cart mr-1"></i> Buy now</button></div>
      
    </div>
    <div class="col-4">
        <img class="d-block w-100" src="{% static '../static/images/ekagra img4.jpg' %}" alt="second slide" style="height:400px;width:400px">
        <p class="prod-desc">this is a mandla art and it is worth buying. it is 12X10 inches</p>
      <div class="btn"><button class="btn btn-primary"><i class="fas fa-shopping-cart mr-1"></i> Buy now</button></div>
      
    </div>
  </div>
</div>


<div class="about" style="margin-left:auto; width:70%; text-align: center; margin-right:auto">
      <div id="getaquote"style="border-bottom: ridge; margin-left: auto; margin-right: auto;width: 100%; margin-bottom: 50px; margin-top: 60px; text-align: center;"><h2>About us</h2></div>
<p>In Hinduism, a basic mandala, also called a yantra, takes the form of a square with four gates containing a circle with a center point. Each gate is in the general shape of a T.[3] Mandalas often have radial balance.[4]

A yantra is similar to a mandala, usually smaller and using a more limited colour palette. It may be a two- or three-dimensional geometric composition used in sadhanas, puja or meditative rituals, and may incorporate a mantra into its design. It is considered to represent the abode of the deity. Each yantra is unique and calls the deity into the presence of the practitioner through the elaborate symbolic geometric designs. According to one scholar, "Yantras function as revelatory symbols of cosmic truths and as instructional charts of the spiritual aspect of human experience"[5]

Many situate yantras as central focus points for Hindu tantric practice. Yantras are not representations, but are lived, experiential, nondual realities. As Khanna describes:

</p>

      <div id="getaquote"style="border-bottom: ridge; margin-left: auto; margin-right: auto;width: 100%; margin-bottom: 10px; margin-top: 60px; text-align: center;"><h2>Contact me</h2></div>

  <div class="my-form">
    <div class="row">
        <form method="post">
          {% csrf_token %}
          {{ form }}


          {% if messages %}
          {% for message in messages %}

          <div class="alert alert-success" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Your mail is sent. Please wait for my response</strong>
          </div>

          {% endfor %}
          {% endif %}
          <input type="submit" value="Submit">
        </form>
      </div>
  </div>


<script>
function slideSwitch() {
    var $active = $('#slideshow DIV.active');

    if ($active.length == 0) $active = $('#slideshow DIV:last');

    // use this to pull the divs in the order they appear in the markup
    var $next = $active.next().length ? $active.next() : $('#slideshow DIV:first');

    $active.addClass('last-active');

    $next.css({
        opacity: 0.0
    })
        .addClass('active')
        .animate({
        opacity: 1.0
    }, 1000, function () {
        $active.removeClass('active last-active');
    });
}

var theInterval;

function startSlide() {
    theInterval = setInterval(slideSwitch,3000);
}

function stopSlide() {
    clearInterval(theInterval);
}

$(function () {
    startSlide();
    $('#slideshow DIV').hover(function () {
        stopSlide();
    }, function () {
        startSlide();
    })
});
</script>

</body>
</html>

{% endblock  %}